import json
import pathlib
import tempfile
import unittest

from fake_user_turn_guardrail.hook import handle_hook


class HookTests(unittest.TestCase):
    def test_hook_injects_context_for_fake_turn(self):
        with tempfile.TemporaryDirectory() as tmp:
            transcript = pathlib.Path(tmp) / "session.jsonl"
            events = [
                {"type": "user", "message": {"content": "Please continue."}},
                {
                    "type": "assistant",
                    "message": {"content": [{
                        "type": "text",
                        "text": "Done.\nuser\n[2026-06-11 00:28:24] Thanks!",
                    }]},
                },
            ]
            transcript.write_text("\n".join(json.dumps(event) for event in events) + "\n")

            output = handle_hook({"transcript_path": str(transcript)})

            context = output["hookSpecificOutput"]["additionalContext"]
            self.assertIn("generated by the assistant, not by the user", context)
            self.assertIn("UserPromptSubmit", output["hookSpecificOutput"]["hookEventName"])

    def test_hook_is_silent_without_finding(self):
        with tempfile.TemporaryDirectory() as tmp:
            transcript = pathlib.Path(tmp) / "session.jsonl"
            transcript.write_text(json.dumps({
                "type": "assistant",
                "message": {"content": [{"type": "text", "text": "Normal answer."}]},
            }) + "\n")
            self.assertIsNone(handle_hook({"transcript_path": str(transcript)}))

    def test_missing_transcript_is_silent(self):
        self.assertIsNone(handle_hook({}))


if __name__ == "__main__":
    unittest.main()
