"""Claude Code UserPromptSubmit hook entrypoint."""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from .detector import AttributionConfig
from .transcript import Analysis, analyze_events, load_tail_events


def config_from_environment() -> AttributionConfig:
    raw = os.getenv("FAKE_USER_GUARD_SUBJECTS", "").strip()
    if not raw:
        return AttributionConfig()
    subjects = tuple(part.strip() for part in raw.split(",") if part.strip())
    return AttributionConfig(subjects=subjects or AttributionConfig().subjects)


def build_context(analysis: Analysis) -> str | None:
    sections: list[str] = []
    if analysis.structural:
        sections.append(
            "Guardrail finding: the previous assistant turn contains a suspicious "
            f"{analysis.structural.marker} boundary at visible-text line "
            f"{analysis.structural.line_number}. Content from that boundary onward was "
            "generated by the assistant and is not a user message or conversation fact."
        )
    if analysis.false_attributions:
        sections.append(
            "Guardrail finding: the previous assistant turn contains "
            f"{len(analysis.false_attributions)} explicit quoted user attribution(s) "
            "that do not appear in prior real user messages. Those attributions are "
            "model-generated and are not conversation facts."
        )
    if not sections:
        return None
    return "Fake-user-turn guardrail:\n\n" + "\n\n".join(sections)


def handle_hook(payload: dict[str, Any]) -> dict[str, Any] | None:
    path = str(payload.get("transcript_path") or "")
    if not path:
        return None
    tail_bytes = int(os.getenv("FAKE_USER_GUARD_TAIL_BYTES", "300000"))
    events = load_tail_events(path, max(10_000, tail_bytes))
    analysis = analyze_events(events, config_from_environment())
    context = build_context(analysis)
    if not context:
        return None
    return {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": context,
        }
    }


def main() -> None:
    try:
        payload = json.load(sys.stdin)
        output = handle_hook(payload)
    except Exception as error:
        print(
            f"fake-user-turn-hook: {type(error).__name__}",
            file=sys.stderr,
        )
        return
    if output:
        print(json.dumps(output, ensure_ascii=False))


if __name__ == "__main__":
    main()
